### PR TITLE
Add screenshot to README.md

### PR DESCRIPTION
**Pull request by trungnt2910**
I've added screenshot to README.md (issue #3) after fixing #2.

### CODE REVIEW

**Comment by trungnt2910** [comment]
Some of the commits here are meaningless, they appear here because of my mistakes with git. These commits however does not affect my work in any way.

**Comment by korli** [comment]
> Some of the commits here are meaningless, they appear here because of my mistakes with git. These commits however does not affect my work in any way.

Please rebase against origin/master and squash related commits together. Thanks!

**Comment by trungnt2910** [comment]
Sorry, I'm new to git, first time I've heard about squashing.

**Comment by humdingerb** [comment]
Yuo may also want to check out "feaure-branches", see https://github.com/haikuports/haikuports/wiki/DevelopmentModel

For your screenshot, I recommend finding a smaller image to show, so the Peek window can be smaller as well.

**Comment by trungnt2910** [comment]
What should I do after squashing offline?

**Comment by trungnt2910** [comment]
About the screenshot, I've resized the window so that it's smaller and fits more nicely to README.md

**Comment by korli** [comment]
> What should I do after squashing offline?

push --force

**Comment by korli** [comment]
There should be maybe 4 commits in your branch. ATM there are 13 commits.

**Comment by trungnt2910** [comment]
> There should be maybe 4 commits in your branch. ATM there are 13 commits.

I cannot get this thing to work? Can you give me a complete and detailed guide on how to do this?

**Comment by trungnt2910** [comment]
Or should I delete my fork and start all the work again?

**Comment by trungnt2910** [comment]
Thanks, squashing finally worked.

**Comment by korli** [comment]
Please squash the first and last commit together.

**Comment by trungnt2910** [comment]
> Please squash the first and last commit together.

@korli is that possible? An attempt to do this resulted in squashing EVERYTHING into one single commit.

**Comment by korli** [comment]
These commits are messy: they mix things which don't get together with incorrect commit messages.
Could you please sort them out?

**Comment by trungnt2910** [comment]
What do you mean by incorrect commit messages?

**Comment by trungnt2910** [comment]
I'm closing this PR, as well as deleting the fork, to replace with a cleaner one.

**Comment by trungnt2910** [comment]
> These commits are messy: they mix things which don't get together with incorrect commit messages.
> Could you please sort them out?

@korli #22 had them fixed.

**Pull request closed without merging**
