### PR TITLE
Added missing header in PListItem.h

### LINKED ISSUE #17: Peek won't compile due to undefined function
The program will not compile due to [this line](https://github.com/HaikuArchives/Peek/blob/b4958e6e781087b4674d73645c011b9605b26b92/source/PListItem.cpp#L19).

### PR DESCRIPTION
**Pull request by alwayslivid**
Resolves #17

### CODE REVIEW

**Comment by korli** [comment]
Why would string.h be needed in PListItem.h?

**Comment by alwayslivid** [comment]
> Why would string.h be needed in PListItem.h?

PListItem.cpp would not compile without it.

**Comment by trungnt2910** [comment]
#19 has already been merged and includes the required header.

**Comment by korli** [comment]
> #19 has already been merged and includes the required header.

Yeah, regrettably it has been merged.

**Comment by owenca** [comment]
I think the right way to fix #2 is to enlarge the file panel to fill the gaps, which can be fixed with layout management.

@trungnt2910 You can push a revert commit first in your PR for #9 and close this PR.

**Comment by trungnt2910** [comment]
> I think the right way to fix #2 is to enlarge the file panel to fill the gaps, which can be fixed with layout management.

Fixed in #21

**Pull request closed without merging**
