### PR TITLE
Filter out incompatible files from the file list/explorer.

### LINKED ISSUE #6: File list filter
It will be nice to add filter that shows all files with correct formats that program can read.

### PR DESCRIPTION
**Pull request by fantoro**
I made it filter out incompatible files by checking if the MIME type starts with `image/`. Let me know if there's anything that needs to be fixed/changed.

Fixes #6

### CODE REVIEW

**Comment by fantoro** [comment]
Force-pushed because I accidentally forgot to sync my clock again lol.

**Comment by humdingerb** [comment]
The app crashes when encountering a link to an image.

**Comment by humdingerb** [comment]
I just discovered that Peek already has this filtering as an option (also crashing on linked images btw).
The options-as-menus (and submenus with submens...) of Peek are a pretty disaster...

**Comment by fantoro** [comment]
So should I just remove my filtering and fix the pre-existing filtering or remove the pre-existing filtering settings and leave out (and fix) my filtering to filter files out by default?

**Comment by humdingerb** [comment]
I'd say keep the existing filtering option, Peek's option will remain a mess...
If you can fix the symlink-crash, that would be nice. In a separate PR, I suppose, as we should close this one, rigth?

**Comment by fantoro** [comment]
> I'd say keep the existing filtering option, Peek's option will remain a mess...
> If you can fix the symlink-crash, that would be nice. In a separate PR, I suppose, as we should close this one, rigth?

Alright.

**Pull request closed without merging**
